import Image from "next/image"

export default function Home(params) {
  return (
    <div className="bg-gradient-to-b from-black to-gray-900">
      <div className="m-auto grid max-w-7xl grid-cols-2 gap-4 space-x-3 space-y-3 p-4 xs:grid-cols-4">
        <p className="col-span-2 self-center font-spotify text-9xl text-white">
          CLICKS
        </p>
        <div className="grid">
          <Image
            alt="hike-clear-sky-1.jpg"
            className="rounded-lg"
            src={"/clicks/hike-clear-sky-1.jpg"}
            width={600}
            height={600}
          />
          <Image
            alt="sea"
            className="rounded-lg"
            src={"/clicks/sea.jpg"}
            width={600}
            height={600}
          />
        </div>
        <Image
          alt="hike-filter-shoes.JPG"
          className="rounded-lg"
          src={"/clicks/hike-filter-shoes.JPG"}
          width={600}
          height={600}
        />
        <Image
          alt="jublie-bulding.jpg"
          className="rounded-lg"
          src={"/clicks/jublie-bulding.jpg"}
          width={600}
          height={600}
        />
        <Image
          alt="plane-glider.jpg"
          className="rounded-lg"
          src={"/clicks/plane-glider.jpg"}
          width={600}
          height={600}
        />
        <Image
          alt="sea-beach-closeup.jpg"
          className="rounded-lg"
          src={"/clicks/sea-beach-closeup.jpg"}
          width="6000"
          height="3600"
        />
        <Image
          alt="forest.jpg"
          className="rounded-lg"
          src={"/clicks/forest.jpg"}
          width={600}
          height={600}
        />
        <Image
          alt="stadium-left-side.jpg"
          className="rounded-lg"
          src={"/clicks/stadium-left-side.jpg"}
          width={600}
          height={600}
        />
        <Image
          alt="hike-1.jpg"
          className="rounded-lg"
          src={"/clicks/hike-1.jpg"}
          width={600}
          height={600}
        />
        <Image
          alt="fog.jpg"
          className="rounded-lg"
          src={"/clicks/fog.jpg"}
          width={600}
          height={600}
        />
        <div className="grid gap-2">
          <Image
            alt="table-bottle.jpg"
            className="rounded-lg"
            src={"/clicks/table-bottle.jpg"}
            width={600}
            height={600}
          />
          <Image
            alt="stadium-center-darker-sky.jpg"
            className="rounded-lg"
            src={"/clicks/stadium-center-darker-sky.jpg"}
            width={600}
            height={600}
          />
        </div>
      </div>
    </div>
  )
}
